version: '3.8'

services:
  web:
    build:
      context: .
      target: app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"

  tests:
    build:
      context: .
      target: tests
    depends_on:
      - web
    environment:
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
